<a href="https://colab.research.google.com/github/luisArthurRodriguesDaSilva/autoProverbs/blob/main/autoProverbious.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def getSpaces(text):
    spaces = []
    for i in range(len(text)):
        if text[i] == ' ':
            spaces.append(i)
    return spaces


def getBiggestSmallest(arraio,n) :
  for index,curr  in enumerate(arraio):
    if curr > n:
      return arraio[index-1]
  return 9000

def divitedText(text, SizeLine):
  spaces = np.array(getSpaces(text))
  volta = 0
  while 1:
    print(spaces)
    volta+=1
    local = getBiggestSmallest(spaces,SizeLine*volta)
    if local == 9000:
      break
    text = text[:local] + '\n' + text[local+1:]
  return text

[ 1  7 11 13 23 29 32 44 50 52 61 63 65 75 79 86 89 99]
[ 1  7 11 13 23 29 32 44 50 52 61 63 65 75 79 86 89 99]
[ 1  7 11 13 23 29 32 44 50 52 61 63 65 75 79 86 89 99]
[ 1  7 11 13 23 29 32 44 50 52 61 63 65 75 79 86 89 99]
É claro que a estrutura atual
da organização exige a
precisão e a definição dos níveis de
motivação departamental.


In [7]:
import json
import tweepy
from random import randrange
from datetime import date

today = date.today().day

with open('/content/drive/MyDrive/biblia/bibleNvi.json','r') as f:
  bible = json.load(f)
with open('/content/drive/MyDrive/keysOfNsei.json','r') as f:
  keys = (json.load(f))[0]

for book  in bible :
  if (book["abbrev"] == "pv"):
    proverbios = book
    break

cap = proverbios['chapters']

cd = cap[today-1]
limit = len(cd)
versicleIndex = randrange(0,limit)

dailyVersicle = cd[versicleIndex]
finalResult = (f"""{dailyVersicle}
provérbios({today}:{versicleIndex+1})""")
print(finalResult)

Não mude de lugar os antigos marcos que limitam as propriedades e que foram colocados por seus antepassados.
pv(22:28)


In [8]:
import numpy as np
#import cv2
from PIL import Image, ImageDraw, ImageFont
import math
#from funcs import *

text = finalResult
imgPath = '/content/drive/MyDrive/62af6d8.jpg'
img = Image.open(imgPath)
[width, height] = img.size
cantofact = 15
sizeOfCanto = int(width/cantofact)
diminuit = 15
fontSize=int(width/diminuit)
[initialWidth,initialHeight] = map(lambda x: int(x/cantofact),[width,height])
limitLine = int(diminuit)
print(limitLine)
convertedText = divitedText(text,limitLine)
print(img.size)

idr = ImageDraw.Draw(img)

font = ImageFont.truetype('/content/drive/MyDrive/fontes/arial.ttf' ,int(fontSize))

idr.text((initialWidth, initialHeight), convertedText, fill=(255, 255, 0), font=font)


newPath = '/teste atual/essa.jpg'

img.save(newPath)

15
[ 3  8 11 17 20 28 35 39 47 50 63 65 69 75 85 89 94]
[ 3  8 11 17 20 28 35 39 47 50 63 65 69 75 85 89 94]
[ 3  8 11 17 20 28 35 39 47 50 63 65 69 75 85 89 94]
[ 3  8 11 17 20 28 35 39 47 50 63 65 69 75 85 89 94]
[ 3  8 11 17 20 28 35 39 47 50 63 65 69 75 85 89 94]
[ 3  8 11 17 20 28 35 39 47 50 63 65 69 75 85 89 94]
[ 3  8 11 17 20 28 35 39 47 50 63 65 69 75 85 89 94]
(1080, 1350)


In [ ]:
auth = tweepy.OAuthHandler(keys['chave1'],keys['chave2'])
auth.set_access_token(keys['chave3'],keys['chave4'])
api = tweepy.API(auth)

api.update_status(finalResult)
api.update_with_media(newPath,)